### ISSUE TITLE
Switch between feet and meter

### ISSUE THREAD

**Issue by realDayaa** [alexsylex/CompassNavigationOverhaul#24]
As an European, I would be nice to view the distance to markers in meters.
Could be implemented as a switch in a MCM menu (#11)

**Comment by alexsylex** [comment]
You have that option in the ini file that comes with the mod in the nexus. Check the options please! I will add the MCM menu when I get it without esp, so you can install/uninstall mid-playthrough.

**Comment by realDayaa** [comment]
Oops, missed that line. Thanks!
