### ISSUE TITLE
Update for the latest Skyrim AE version

### ISSUE THREAD

**Issue by JoXW100** [alexsylex/CompassNavigationOverhaul#27]
Compass Navigation Overhaul Infinity UI cause CTD for the latest Skyrim AE version.
 
 A fix has been posted on [reddit](https://www.reddit.com/r/skyrimmods/comments/1asxo4d/release_compass_navigation_overhaul_161170_read/).

**Comment by alexsylex** [comment]
Thanks! I'm on it ;)

**Comment by alexsylex** [comment]
Done :)
